/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DB.DBConnection;
import static GUI.UploadData.id;
import static GUI.UploadData.nama;
import static GUI.UploadData.telepon;
import MODEL.Akun;
import carseeker.CarSeeker;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Chiesaafandy
 */
public class Login extends javax.swing.JFrame {
    
    static Connection conn;
    static Statement st;
    static String sql;
    PreparedStatement ps;
    static ResultSet rs;
    Akun akun;
    String email;
    int id;
    
    /**
     * Creates new form Login
     */
    public Login() {
        
        
        conn = new DBConnection().setConnection();
        initComponents();
        setLocationRelativeTo(this);
        setSize(800,600);
        setLocation(200,100);

        setResizable(false);
    }
    
    class validateLogin{
        private void btnLogin(){
                    String email = tf_email.getText();
        String pass = tf_pass.getText();
        
        
        try {
            sql = "SELECT * FROM `dataakun` WHERE `email`= " + "'"+ email +"'";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            
                while(rs.next()){
                    akun = new Akun(
                            rs.getInt("id_akun"),
                            rs.getString("nama"),
                            rs.getString("email"),
                            rs.getString("password"),
                            rs.getString("phone"));
                    
                    
                }
                
        if(email.equals(akun.getEmail())&& pass.equals(akun.getPassword())){
            
            String nama = akun.getNama();
            String telepon = akun.getTelephone();
            int id = akun.getId();
            MainMenu mm = new MainMenu(nama, telepon, id);
            
            JOptionPane.showMessageDialog(null, "Selamat Datang " + akun.getNama() + " Di Carseeker!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            
            
            mm.setVisible(true);
            dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Password Tidak Cocok", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
                
        } catch (Exception e) {
            System.out.println("Error" + e.getMessage());
            JOptionPane.showMessageDialog(null, "Akun Tidak Tersedia\n"
                    + "Silahkan Periksa Kembali Akun Anda atau Buat Akun Baru", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_bg = new javax.swing.JPanel();
        pnl_logo = new javax.swing.JLabel();
        pnl_login = new javax.swing.JPanel();
        lb_login = new javax.swing.JLabel();
        lb_email = new javax.swing.JLabel();
        lb_pass = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        tf_pass = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        btn_register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_bg.setBackground(new java.awt.Color(200, 217, 237));
        pnl_bg.setToolTipText("");
        pnl_bg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnl_bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImageIcon imageIcon = new ImageIcon(new ImageIcon(getClass().getResource("/CARSEEKER/CarSeekerLogo.jpeg")).getImage().getScaledInstance(400, 400, Image.SCALE_DEFAULT));
        pnl_logo.setIcon(imageIcon);
        pnl_bg.add(pnl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 400, 407));

        pnl_login.setBackground(new java.awt.Color(255, 255, 255));
        pnl_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_login.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        lb_login.setText("Login");
        pnl_login.add(lb_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 79, -1));

        lb_email.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lb_email.setText("Email");
        pnl_login.add(lb_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 79, -1));

        lb_pass.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lb_pass.setText("Password");
        pnl_login.add(lb_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        pnl_login.add(tf_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 310, 35));
        pnl_login.add(tf_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 310, 35));

        btn_login.setBackground(new java.awt.Color(153, 204, 255));
        btn_login.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_login.setText("Masuk");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        pnl_login.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 255, 310, 40));

        btn_register.setBackground(new java.awt.Color(255, 255, 255));
        btn_register.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_register.setText("Daftar akun");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        pnl_login.add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 310, 35));

        pnl_bg.add(pnl_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 350, 407));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        Register reg = new Register();
        reg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_registerActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        Login.validateLogin ic = new Login.validateLogin();

        ic.btnLogin();

    }//GEN-LAST:event_btn_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_login;
    private javax.swing.JLabel lb_pass;
    private javax.swing.JPanel pnl_bg;
    private javax.swing.JPanel pnl_login;
    private javax.swing.JLabel pnl_logo;
    private javax.swing.JTextField tf_email;
    private javax.swing.JPasswordField tf_pass;
    // End of variables declaration//GEN-END:variables
}
