/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DB.DBConnection;
import MODEL.Akun;
import MODEL.Menu;
import carseeker.CarSeeker;
import com.sun.java.accessibility.util.SwingEventMonitor;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.event.CaretEvent;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Chiesaafandy
 */
public class MainMenu extends javax.swing.JFrame {

    static Connection conn;
    static Statement st;
    static String sql;
    PreparedStatement ps;
    static ResultSet rs;
    Menu datamenu;
    public static String nama,telepon;
    public static int id, id_mobil;
    /**
     * Creates new form MainMenu
     */
    public MainMenu(String nama, String telepon, int id) {
        this.nama = nama;
        this.telepon = telepon;
        this.id = id;
        
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(getClass().getResource("/CARSEEKER/CarSeekerLogo.jpeg")).getImage().getScaledInstance(120, 120, Image.SCALE_DEFAULT)); 
        
        
        
        
        setLocationRelativeTo(this);
        setSize(800,600);
        setLocation(200,100);

        setResizable(false);
        
        conn = new DBConnection().setConnection();
        initComponents();
        bikinLabel();
        lb_nama.setText(nama);
        lb_tlp.setText(telepon);
        System.out.println("ini idnya"+id);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_bg = new javax.swing.JPanel();
        pnl_menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnl_logo = new javax.swing.JLabel();
        lb_tlp = new javax.swing.JLabel();
        lb_nama = new javax.swing.JLabel();
        btn_jual1 = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        pnl_post = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_bg.setBackground(new java.awt.Color(204, 204, 204));

        pnl_menu.setBackground(new java.awt.Color(200, 217, 237));
        pnl_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Selamat Datang");
        pnl_menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        ImageIcon imageIcon = new ImageIcon(new ImageIcon(getClass().getResource("/CARSEEKER/CarSeekerLogo.jpeg")).getImage().getScaledInstance(160, 160, Image.SCALE_DEFAULT));
        pnl_logo.setIcon(imageIcon);
        pnl_menu.add(pnl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, 160));

        lb_tlp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnl_menu.add(lb_tlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 190, 30));

        lb_nama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnl_menu.add(lb_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 190, 30));

        btn_jual1.setBackground(new java.awt.Color(255, 255, 255));
        btn_jual1.setText("JUAL MOBIL");
        btn_jual1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jual1ActionPerformed(evt);
            }
        });
        pnl_menu.add(btn_jual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 190, 50));

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        pnl_menu.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, -1, -1));

        pnl_post.setBackground(new java.awt.Color(255, 255, 255));
        pnl_post.setPreferredSize(new java.awt.Dimension(600, 600));
        pnl_post.setLayout(new java.awt.GridLayout(0, 4, 5, 5));

        javax.swing.GroupLayout pnl_bgLayout = new javax.swing.GroupLayout(pnl_bg);
        pnl_bg.setLayout(pnl_bgLayout);
        pnl_bgLayout.setHorizontalGroup(
            pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bgLayout.createSequentialGroup()
                .addComponent(pnl_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_post, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_bgLayout.setVerticalGroup(
            pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_post, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_jual1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jual1ActionPerformed
        UploadData ud = new UploadData(nama, telepon, id);
        ud.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_jual1ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        
        
        int jawab = JOptionPane.showOptionDialog(this, 
                    "Ingin Logout?", 
                    "Logout", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE, null, null, null);
    
    if(jawab == JOptionPane.YES_OPTION){
        JOptionPane.showMessageDialog(this, "Anda Berhasil Logout");
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }
    
    }//GEN-LAST:event_btnLogoutActionPerformed

    
    public void bikinLabel(){
        
        
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(getClass().getResource("/CARSEEKER/CarSeekerLogo.jpeg")).getImage().getScaledInstance(120, 120, Image.SCALE_DEFAULT));
        
        ArrayList<Menu> daftar = daftarmenu();
        Object[] row = new Object[6];
        String Tampilan;
        int size = daftar.size();
        
        System.out.println(daftar.size());
        if(size > 12){
            System.out.println("slot penuh");
            size = 12;
        }
        
        JLabel lb_postingan[] = new JLabel[size];
        
        
        
        for (int i = 0; i < size; i++) {
            lb_postingan[i] = new JLabel();
            lb_postingan[i].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lb_postingan[i].setIcon(imageIcon);
            
             
             row[0] = daftar.get(i).getId();
             row[1] = daftar.get(i).getJudul();
             row[2] = daftar.get(i).getMerek();
             row[3] = daftar.get(i).getModel();
             row[4] = daftar.get(i).getHarga();
             row[5] = daftar.get(i).getGambar();
             System.out.println(row[5].toString());
             
             int id_data, harga;
             String judul, merek, model;
             
             
             
             id_data = (Integer) row[0];
             judul = row[1].toString();
             merek = row[2].toString();
             model = row[3].toString();
             harga = (Integer) row[4];
             
             DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
             DecimalFormatSymbols formatRp = new DecimalFormatSymbols();

             formatRp.setCurrencySymbol("Rp. ");
             formatRp.setMonetaryDecimalSeparator(',');
             formatRp.setGroupingSeparator('.');

             kursIndonesia.setDecimalFormatSymbols(formatRp);
             
             System.out.printf("Harga : %s %n", kursIndonesia.format(harga));
             
             byte[] img = daftar.get(i).getGambar();
             
             ImageIcon image = new ImageIcon(img);
                    Image im = image.getImage();
                    Image myImg = im.getScaledInstance(120, 120,Image.SCALE_SMOOTH);
                    ImageIcon newImage = new ImageIcon(myImg);
                    lb_postingan[i].setIcon(newImage);
            
                    
             Tampilan = "<html> <div align = 'center'>"+judul + "<br/>" + merek + " : " + model + "<br/>"+ kursIndonesia.format(harga) + "</div></html>";
             lb_postingan[i].setText(Tampilan);
        
        
            
            lb_postingan[i].setVerticalAlignment(javax.swing.SwingConstants.TOP);
            lb_postingan[i].setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            lb_postingan[i].setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            lb_postingan[i].setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            
            final int k = i;
            
            lb_postingan[i].addMouseListener(new java.awt.event.MouseAdapter() {
            @Override 
            public void mouseClicked(java.awt.event.MouseEvent evt) {                
                int id_post = id_data ;
                System.out.println("id post" + id_data);
                id_mobil = id_post;
                
                Post ps = new Post(nama,telepon,id,id_mobil);
                System.out.println(k);
                System.out.println(id);
                
                ps.setVisible(true);
                dispose();
            }
            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
               lb_postingan[k].setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
               lb_postingan[k].setBackground(new java.awt.Color(153, 204, 255));
               
            }
            @Override 
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                System.out.println(k);
                lb_postingan[k].setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                lb_postingan[k].setBackground(Color.black);
            }
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                System.out.println(k);
                lb_postingan[k].setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                lb_postingan[k].setBackground(Color.white);
            }
        });

            pnl_post.add(lb_postingan[i]);
            
        
        }
        
        pnl_post.validate();
        pnl_post.repaint();
        
    }
    
    public ArrayList<Menu> daftarmenu(){
    ArrayList<Menu> daftarmenu = new ArrayList<>();
        try {
            sql = "SELECT * FROM datamobil ORDER BY id_mobil ASC";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            
                while(rs.next()){
                    datamenu = new Menu(
                            rs.getInt("id_mobil"),
                            rs.getString("judul_post"),
                            rs.getString("merk"),
                            rs.getString("model"),
                            rs.getInt("harga"),
                            rs.getBytes("gambar"));
                    daftarmenu.add(datamenu);
                    
                    System.out.println(daftarmenu.get(0).getJudul());
                    System.out.println(daftarmenu.get(0).getMerek());
                }
        } catch (Exception e) {
            System.out.println("Error" + e.getMessage());
        }
        return daftarmenu;
    }
    

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu(sql, sql, WIDTH).setVisible(true);
                
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btn_jual1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_nama;
    private javax.swing.JLabel lb_tlp;
    private javax.swing.JPanel pnl_bg;
    private javax.swing.JLabel pnl_logo;
    private javax.swing.JPanel pnl_menu;
    private javax.swing.JPanel pnl_post;
    // End of variables declaration//GEN-END:variables
}
