/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DB.DBConnection;
import MODEL.Akun;
import MODEL.Penjual;
import Model.Mobil;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import javax.swing.ImageIcon;


    
/**
 *
 * @author Aan Furqan
 */
public class Post extends javax.swing.JFrame {

    static Connection conn;
    static Statement st;
    static String sql;
    PreparedStatement ps;
    static ResultSet rs;
    Mobil mobil;
    Penjual penjual;
    
    public static String nama,telepon;
    public static int id, id_mobil, id_penjual;
    
    /**
     * Creates new form Post
     */
    public Post(String nama, String telepon, int id, int id_mobil) {
        
        Post.nama = nama;
        Post.telepon = telepon;
        Post.id = id;
        Post.id_mobil = id_mobil;
        
        conn = new DBConnection().setConnection();
        setLocationRelativeTo(this);
        setSize(800,600);
        setLocation(200,100);

        setResizable(false);
        
        initComponents();
        tampilDataMobil();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbImage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaDesc = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbTipeMobil = new javax.swing.JLabel();
        lbMerek = new javax.swing.JLabel();
        lbModel = new javax.swing.JLabel();
        lbVarian = new javax.swing.JLabel();
        lbTahun = new javax.swing.JLabel();
        lbKapasitasMesin = new javax.swing.JLabel();
        lbKilometer = new javax.swing.JLabel();
        lbPenumpang = new javax.swing.JLabel();
        lbTransmisi = new javax.swing.JLabel();
        lbWarna = new javax.swing.JLabel();
        lbTipeMobil1 = new javax.swing.JLabel();
        lbMerek1 = new javax.swing.JLabel();
        lbModel1 = new javax.swing.JLabel();
        lbVarian1 = new javax.swing.JLabel();
        lbTahun1 = new javax.swing.JLabel();
        lbKapasitasMesin1 = new javax.swing.JLabel();
        lbTransmisi1 = new javax.swing.JLabel();
        lbPenumpang1 = new javax.swing.JLabel();
        lbKilometer1 = new javax.swing.JLabel();
        lbWarna1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbJudulIklan = new javax.swing.JLabel();
        lbHarga = new javax.swing.JLabel();
        btnWA = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lb_hargaFront = new javax.swing.JLabel();
        lbHarga1 = new javax.swing.JLabel();
        lb_nama = new javax.swing.JLabel();
        lbHarga2 = new javax.swing.JLabel();
        lb_telp = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(200, 217, 237));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(250, 250));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 250, 250));

        txtareaDesc.setColumns(20);
        txtareaDesc.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtareaDesc.setRows(5);
        txtareaDesc.setText("Deskripsi Produk :");
        jScrollPane1.setViewportView(txtareaDesc);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 370, 200));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Spesifikasi Ringkas");

        lbTipeMobil.setText("Tipe Mobil");

        lbMerek.setText("Merek");

        lbModel.setText("Model");

        lbVarian.setText("Varian");

        lbTahun.setText("Tahun");

        lbKapasitasMesin.setText("Kapasitas Mesin");

        lbKilometer.setText("Kilometer");

        lbPenumpang.setText("Penumpang");

        lbTransmisi.setText("Transmisi");

        lbWarna.setText("Warna");

        lbTipeMobil1.setText("Tipe Mobil");

        lbMerek1.setText("Merek");

        lbModel1.setText("Model");

        lbVarian1.setText("Varian");

        lbTahun1.setText("Tahun");

        lbKapasitasMesin1.setText("Kapasitas Mesin");

        lbTransmisi1.setText("Transmisi");

        lbPenumpang1.setText("Penumpang");

        lbKilometer1.setText("Kilometer");

        lbWarna1.setText("Warna");

        jLabel6.setText(":");

        jLabel7.setText(":");

        jLabel8.setText(":");

        jLabel9.setText(":");

        jLabel10.setText(":");

        jLabel11.setText(":");

        jLabel12.setText(":");

        jLabel13.setText(":");

        jLabel14.setText(":");

        jLabel15.setText(":");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbTipeMobil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbMerek)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbWarna)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbModel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbVarian)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbTahun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbKapasitasMesin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbTransmisi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbPenumpang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbKilometer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTipeMobil1)
                            .addComponent(lbMerek1)
                            .addComponent(lbModel1)
                            .addComponent(lbVarian1)
                            .addComponent(lbTahun1)
                            .addComponent(lbKapasitasMesin1)
                            .addComponent(lbKilometer1)
                            .addComponent(lbPenumpang1)
                            .addComponent(lbTransmisi1)
                            .addComponent(lbWarna1))
                        .addGap(46, 46, 46))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbTipeMobil)
                        .addGap(18, 18, 18)
                        .addComponent(lbMerek)
                        .addGap(18, 18, 18)
                        .addComponent(lbModel)
                        .addGap(18, 18, 18)
                        .addComponent(lbVarian)
                        .addGap(18, 18, 18)
                        .addComponent(lbTahun)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbKapasitasMesin)
                            .addComponent(jLabel11)
                            .addComponent(lbKapasitasMesin1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTransmisi)
                            .addComponent(jLabel12)
                            .addComponent(lbTransmisi1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPenumpang)
                            .addComponent(jLabel13)
                            .addComponent(lbPenumpang1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbKilometer)
                            .addComponent(jLabel14)
                            .addComponent(lbKilometer1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbWarna)
                            .addComponent(jLabel15)
                            .addComponent(lbWarna1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTipeMobil1)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMerek1)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbModel1)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbVarian1)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTahun1)
                            .addComponent(jLabel10))))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 310, 450));

        lbJudulIklan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbJudulIklan.setText("Judul Iklan");
        jPanel1.add(lbJudulIklan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 154, -1));

        lbHarga.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbHarga.setText("Harga:");
        jPanel1.add(lbHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        btnWA.setBackground(new java.awt.Color(51, 204, 0));
        btnWA.setText("WhatsApp");
        btnWA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWAActionPerformed(evt);
            }
        });
        jPanel1.add(btnWA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 116, -1));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back To Menu");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, 310, -1));

        lb_hargaFront.setText("Harga");
        jPanel1.add(lb_hargaFront, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        lbHarga1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbHarga1.setText("Penjual :");
        jPanel1.add(lbHarga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        lb_nama.setText("Nama");
        jPanel1.add(lb_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        lbHarga2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbHarga2.setText("No.Telepon:");
        jPanel1.add(lbHarga2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        lb_telp.setText("Telepon");
        jPanel1.add(lb_telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 801, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnWAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWAActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MainMenu mm = new MainMenu(nama, telepon, id);
        mm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Post(nama, telepon, id, id_mobil).setVisible(true);
            }
        });
    }
    
    public ArrayList<Penjual> dataPenjual(){
    ArrayList<Penjual> dataPenjual = new ArrayList<>();
        try {
            sql = "SELECT * FROM `dataakun` WHERE `id_akun` = " + id_penjual;
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            
                while(rs.next()){
                    penjual = new Penjual(
                            rs.getInt("id_akun"),
                            rs.getString("nama"),
                            rs.getString("phone"));
                    dataPenjual.add(penjual);
                }
        } catch (Exception e) {
            System.out.println("Error" + e.getMessage());
        }
        return dataPenjual;
    }
    
    public ArrayList<Mobil> dataMobil(){
    ArrayList<Mobil> dataMobil = new ArrayList<>();
        try {
            sql = "SELECT * FROM `datamobil` WHERE `id_mobil` = " + id_mobil;
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            
                while(rs.next()){
                    mobil = new Mobil(
                            rs.getInt("id_mobil"), 
                            rs.getInt("id_akun"), 
                            rs.getString("tanggal_post"), 
                            rs.getString("tipe_mobil"),
                            rs.getString("merk"), 
                            rs.getString("model"), 
                            rs.getString("varian"),
                            rs.getString("tahun"),
                            rs.getString("warna"),
                            rs.getString("kapasitas_mesin"),
                            rs.getString("transmisi"),
                            rs.getString("kapasitas_penumpang"),
                            rs.getInt("kilometer"), 
                            rs.getString("deskripsi_mobil"),
                            rs.getString("judul_post"),
                            rs.getInt("harga"), 
                            rs.getBytes("gambar"));
                    dataMobil.add(mobil);
                    
                }
        } catch (Exception e) {
            System.out.println("Error" + e.getMessage());
        }
        return dataMobil;
    }
    
    public void tampilDataMobil(){
        ArrayList<Mobil> daftar = dataMobil();
         Object[] row = new Object[13];
         
         for(int i=0; i<daftar.size(); i++){
             row[0] = daftar.get(i).getTipe_mobil();
             row[1] = daftar.get(i).getMerk();
             row[2] = daftar.get(i).getModel();
             row[3] = daftar.get(i).getVarian();
             row[4] = daftar.get(i).getTahun();
             row[5] = daftar.get(i).getKapasitas_mesin();
             row[6] = daftar.get(i).getTransmisi();
             row[7] = daftar.get(i).getKapasitas_penumpang();
             row[8] = daftar.get(i).getKilometer();
             row[9] = daftar.get(i).getWarna();
             row[10] = daftar.get(i).getDeskripsi_mobil();
             row[11] = daftar.get(i).getId_akun();
             row[12] = daftar.get(i).getHarga();
             
             int harga;
             harga = (Integer) row[12];
             
             DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
             DecimalFormatSymbols formatRp = new DecimalFormatSymbols();

             formatRp.setCurrencySymbol("Rp. ");
             formatRp.setMonetaryDecimalSeparator(',');
             formatRp.setGroupingSeparator('.');

             kursIndonesia.setDecimalFormatSymbols(formatRp);
             
             lb_hargaFront.setText(kursIndonesia.format(harga));
             
             id_penjual = (Integer) row[11];
             System.out.println("id penjual =" + id_penjual);
             
             lbTipeMobil1.setText(row[0].toString());
             lbMerek1.setText(row[1].toString());
             lbModel1.setText(row[2].toString());
             lbVarian1.setText(row[3].toString());
             lbTahun1.setText(row[4].toString());
             lbKapasitasMesin1.setText(row[5].toString());
             lbTransmisi1.setText(row[6].toString());
             lbPenumpang1.setText(row[7].toString());
             lbKilometer1.setText(row[8].toString());
             lbWarna1.setText(row[9].toString());
             txtareaDesc.setText("Deskripsi Produk: \n \n" + row[10].toString());
             
             byte[] img = daftar.get(i).getGambar();
             
             ImageIcon image = new ImageIcon(img);
                    Image im = image.getImage();
                    Image myImg = im.getScaledInstance(250, 250,Image.SCALE_SMOOTH);
                    ImageIcon newImage = new ImageIcon(myImg);
                    lbImage.setIcon(newImage);
         }
         
        ArrayList<Penjual> jual = dataPenjual();
        
        for (int i = 0; i < jual.size(); i++) {
             row[0] = jual.get(i).getId();
             row[1] = jual.get(i).getNama();
             row[2] = jual.get(i).getTelephone();
             
             lb_nama.setText(row[1].toString());
             lb_telp.setText(row[2].toString());
            
        }
      }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnWA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbHarga;
    private javax.swing.JLabel lbHarga1;
    private javax.swing.JLabel lbHarga2;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbJudulIklan;
    private javax.swing.JLabel lbKapasitasMesin;
    private javax.swing.JLabel lbKapasitasMesin1;
    private javax.swing.JLabel lbKilometer;
    private javax.swing.JLabel lbKilometer1;
    private javax.swing.JLabel lbMerek;
    private javax.swing.JLabel lbMerek1;
    private javax.swing.JLabel lbModel;
    private javax.swing.JLabel lbModel1;
    private javax.swing.JLabel lbPenumpang;
    private javax.swing.JLabel lbPenumpang1;
    private javax.swing.JLabel lbTahun;
    private javax.swing.JLabel lbTahun1;
    private javax.swing.JLabel lbTipeMobil;
    private javax.swing.JLabel lbTipeMobil1;
    private javax.swing.JLabel lbTransmisi;
    private javax.swing.JLabel lbTransmisi1;
    private javax.swing.JLabel lbVarian;
    private javax.swing.JLabel lbVarian1;
    private javax.swing.JLabel lbWarna;
    private javax.swing.JLabel lbWarna1;
    private javax.swing.JLabel lb_hargaFront;
    private javax.swing.JLabel lb_nama;
    private javax.swing.JLabel lb_telp;
    private javax.swing.JTextArea txtareaDesc;
    // End of variables declaration//GEN-END:variables
}
